library(raster)
library(vctrs)
library(tibble)
library(GISTools)
library(readr)
library(dplyr)
library(lubridate)
library(xtable)
library(ggplot2)
library(rgeos)
library(rgdal)
library(maptools)
library(broom)

counties <- shapefile("../data/PA_counties.shp")
